version: '3'

services:
  db:
    image: postgres:14
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '543:5432'
    # healthcheck:
    #   test:
    #     ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  redis_data:
  pg_data:

