# Generated by Django 5.0.2 on 2024-02-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
