# Generated by Django 5.0.2 on 2024-02-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status_code',
            field=models.TextField(blank=True, default='200', null=True),
        ),
    ]
